name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # 👈 required for OIDC (federated login)
  contents: read    # 👈 required to checkout code

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: SERVICE_PRINCIPAL   # 👈 use this instead of id-token

      - uses: azure/webapps-deploy@v2
        with:
          app-name: hello-azure-nodejs-web
          slot-name: Production
